version: "3.8"

services:
  db:
    image: postgres:16
    container_name: lastblock-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lastblock
    ports:
      - "5432:5432" # only expose this for local dev if needed
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
